/**
 * Hero Academy \u2014 Today\u2019s Mission generator.
 *
 * POST /api/mission/today
 * Body: {
 *   day_of_week:   number (0\u20136),
 *   day_name:      string,
 *   zone_progress: { [zoneId]: number 0\u2013100 },
 *   recent_zones:  string[]  // zones visited in last 3 days (most recent first)
 *   homework_due:  boolean
 *   homework_topic:string|null
 * }
 *
 * Returns: {
 *   warmup:  { zone_id, title, blurb, minutes },
 *   stretch: { zone_id, title, blurb, minutes },
 *   win:     { zone_id, title, blurb, minutes },
 *   total_minutes: number,
 *   unlock_hint:   string   // e.g. "Finish all 3 and unlock Aurora the Aviator!"
 * }
 *
 * Generated by Claude Haiku with strict JSON output. Falls back to a
 * deterministic mix if the model is unavailable.
 */

const HAIKU_MODEL = 'claude-haiku-4-5';

// Subject/zone pool the model is allowed to pick from. Hero Hall is a trophy
// room \u2014 fine as a \"win\" celebration step, but not a learning task.
const ZONES = [
  { id: 'word-tower',  subject: 'reading',  label: 'Word Tower',        learn: true,  est: 7 },
  { id: 'story-time',  subject: 'reading',  label: 'Story Time',        learn: true,  est: 6 },
  { id: 'number-lab',  subject: 'math',     label: 'Number Lab',        learn: true,  est: 8 },
  { id: 'discovery',   subject: 'science',  label: 'Discovery Dome',    learn: true,  est: 6 },
  { id: 'explorer',    subject: 'social',   label: 'Explorer\u2019s Hall', learn: true,  est: 7 },
  { id: 'writing',     subject: 'writing',  label: 'Story Lab',         learn: true,  est: 8 },
  { id: 'hero-hall',   subject: 'trophy',   label: 'Hero Hall',         learn: false, est: 3 },
];

const UNLOCK_HINTS = [
  'Finish all 3 and unlock a surprise from the Squad!',
  'Three steps to a new character today.',
  'Complete the mission to grow your hero level!',
  'Crush all three and Ms. Humphrey will celebrate with you.',
];

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });

  let body = req.body;
  if (typeof body === 'string') { try { body = JSON.parse(body); } catch (_) { body = {}; } }
  if (!body || typeof body !== 'object') body = {};

  const zoneProgress = body.zone_progress || {};
  const recentZones = Array.isArray(body.recent_zones) ? body.recent_zones : [];
  const dayName = String(body.day_name || dayNameFromNumber(body.day_of_week));
  const homeworkDue = !!body.homework_due;
  const homeworkTopic = body.homework_topic || null;

  const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;

  let mission;
  if (ANTHROPIC_KEY) {
    try {
      mission = await generateWithHaiku({
        ANTHROPIC_KEY, dayName, zoneProgress, recentZones, homeworkDue, homeworkTopic,
      });
    } catch (e) {
      mission = null;
    }
  }
  if (!mission) mission = fallbackMission({ zoneProgress, recentZones, homeworkDue });

  // Final shape validation
  mission = validateAndPatch(mission);

  return res.status(200).json(mission);
}

function dayNameFromNumber(n) {
  const names = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  if (typeof n === 'number' && n >= 0 && n <= 6) return names[n];
  return names[new Date().getDay()];
}

async function generateWithHaiku({ ANTHROPIC_KEY, dayName, zoneProgress, recentZones, homeworkDue, homeworkTopic }) {
  const zonePool = ZONES.map((z) => ({
    id: z.id,
    label: z.label,
    subject: z.subject,
    is_learning: z.learn,
    progress_pct: zoneProgress[z.id] || 0,
    minutes_estimate: z.est,
  }));

  const systemPrompt = [
    'You are Ms. Humphrey designing today\u2019s 25-minute homeschool mission for Nigel \u2014 7 years old, 2nd grade, Maryland.',
    '',
    'Pick EXACTLY 3 zones from the allowed pool, in this order:',
    '  1. warmup   \u2014 something fun and easy, ideally something he\u2019s already comfortable with',
    '  2. stretch  \u2014 the real work for the day, in a subject he hasn\u2019t touched recently or shows lowest progress',
    '  3. win      \u2014 a quick crowd-pleaser to finish strong',
    '',
    'Rules:',
    '  - All three must come from the allowed pool.',
    '  - Cover at least 2 different subjects across the 3 picks.',
    '  - Avoid picking the same zone Nigel did most recently as the warmup, unless nothing else fits.',
    '  - If homework_due is true, the stretch MUST be \"number-lab\" (homework is math).',
    '  - Each blurb is ONE short sentence written TO Nigel (\"Practice your ch- words with Webly.\") \u2014 not to parents.',
    '  - Minutes per step should be realistic: warmup ~5\u20137, stretch ~8\u201310, win ~3\u20136. Total close to 25.',
    '  - Output strictly valid JSON, nothing else. No markdown, no prose, no code fences.',
    '',
    'JSON shape:',
    '{',
    '  "warmup":  { "zone_id": "...", "title": "...", "blurb": "...", "minutes": 0 },',
    '  "stretch": { "zone_id": "...", "title": "...", "blurb": "...", "minutes": 0 },',
    '  "win":     { "zone_id": "...", "title": "...", "blurb": "...", "minutes": 0 },',
    '  "total_minutes": 0,',
    '  "unlock_hint": "..."',
    '}',
  ].join('\n');

  const userPrompt = [
    'Day: ' + dayName,
    'Homework due today: ' + (homeworkDue ? ('yes (topic: ' + (homeworkTopic || 'math') + ')') : 'no'),
    'Recently visited zones (newest first): ' + (recentZones.length ? recentZones.join(', ') : 'none'),
    '',
    'Allowed zone pool with current progress:',
    JSON.stringify(zonePool, null, 2),
    '',
    'Design today\u2019s mission. Return JSON only.',
  ].join('\n');

  const r = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': ANTHROPIC_KEY,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: HAIKU_MODEL,
      max_tokens: 600,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    }),
  });
  if (!r.ok) throw new Error('anthropic ' + r.status);
  const json = await r.json();
  const text = (json.content || [])
    .filter((b) => b.type === 'text')
    .map((b) => b.text)
    .join('')
    .trim();
  // Strip code fences if present
  const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/i, '').trim();
  const parsed = JSON.parse(cleaned);
  return parsed;
}

function fallbackMission({ zoneProgress, recentZones, homeworkDue }) {
  // Pick least-recently-visited learning zones with lowest progress first.
  const recent = new Set(recentZones.slice(0, 2));
  const candidates = ZONES.filter((z) => z.learn).slice();
  candidates.sort((a, b) => {
    var aRecent = recent.has(a.id) ? 1 : 0;
    var bRecent = recent.has(b.id) ? 1 : 0;
    if (aRecent !== bRecent) return aRecent - bRecent;
    return (zoneProgress[a.id] || 0) - (zoneProgress[b.id] || 0);
  });

  var warmupPool = ZONES.filter((z) => z.learn).slice().sort((a, b) => (zoneProgress[b.id] || 0) - (zoneProgress[a.id] || 0));
  var warmup = warmupPool[0] || candidates[0];
  var stretchPool = candidates.filter((z) => z.id !== warmup.id);
  if (homeworkDue) {
    var nl = stretchPool.find((z) => z.id === 'number-lab') || ZONES.find((z) => z.id === 'number-lab');
    if (nl) stretchPool = [nl].concat(stretchPool.filter((z) => z.id !== 'number-lab'));
  }
  var stretch = stretchPool[0];
  var win = candidates.find((z) => z.id !== warmup.id && z.id !== stretch.id) || ZONES.find((z) => z.id === 'hero-hall');

  return {
    warmup: {
      zone_id: warmup.id,
      title: warmup.label,
      blurb: 'Warm up with something you already love.',
      minutes: Math.min(7, warmup.est),
    },
    stretch: {
      zone_id: stretch.id,
      title: stretch.label,
      blurb: homeworkDue && stretch.id === 'number-lab'
        ? 'Knock out today\u2019s homework, hero.'
        : 'Today\u2019s real challenge \u2014 take your time.',
      minutes: Math.max(8, stretch.est),
    },
    win: {
      zone_id: win.id,
      title: win.label,
      blurb: 'Finish strong with a quick win.',
      minutes: Math.min(5, win.est || 5),
    },
    total_minutes: 20,
    unlock_hint: UNLOCK_HINTS[Math.floor(Math.random() * UNLOCK_HINTS.length)],
  };
}

function validateAndPatch(m) {
  if (!m || typeof m !== 'object') m = {};
  const pool = new Set(ZONES.map((z) => z.id));
  ['warmup', 'stretch', 'win'].forEach((slot) => {
    if (!m[slot] || typeof m[slot] !== 'object') m[slot] = {};
    var step = m[slot];
    if (!pool.has(step.zone_id)) {
      // Patch invalid zone_id with a sensible default
      var fallbacks = { warmup: 'discovery', stretch: 'number-lab', win: 'hero-hall' };
      step.zone_id = fallbacks[slot];
      var z = ZONES.find((zz) => zz.id === step.zone_id);
      step.title = z ? z.label : step.zone_id;
    }
    if (typeof step.title !== 'string' || !step.title) {
      var z2 = ZONES.find((zz) => zz.id === step.zone_id);
      step.title = z2 ? z2.label : step.zone_id;
    }
    if (typeof step.blurb !== 'string') step.blurb = '';
    step.blurb = String(step.blurb).slice(0, 140);
    if (typeof step.minutes !== 'number' || step.minutes < 1 || step.minutes > 30) step.minutes = 6;
    step.minutes = Math.round(step.minutes);
  });
  m.total_minutes = (m.warmup.minutes || 0) + (m.stretch.minutes || 0) + (m.win.minutes || 0);
  if (typeof m.unlock_hint !== 'string' || !m.unlock_hint) {
    m.unlock_hint = UNLOCK_HINTS[0];
  }
  m.unlock_hint = String(m.unlock_hint).slice(0, 160);
  return m;
}
