/**
 * Hero Academy \u2014 Today\u2019s Mission generator.
 *
 * POST /api/mission/today
 * Body: {
 *   day_of_week:   number (0\u20136),
 *   day_name:      string,
 *   zone_progress: { [zoneId]: number 0\u2013100 },
 *   recent_zones:  string[]  // zones visited in last 3 days (most recent first)
 *   homework_due:  boolean
 *   homework_topic:string|null
 * }
 *
 * Returns: {
 *   warmup:  { zone_id, title, blurb, minutes },
 *   stretch: { zone_id, title, blurb, minutes },
 *   win:     { zone_id, title, blurb, minutes },
 *   total_minutes: number,
 *   unlock_hint:   string   // e.g. "Finish all 3 and unlock Aurora the Aviator!"
 * }
 *
 * Generated by Claude Haiku with strict JSON output. Falls back to a
 * deterministic mix if the model is unavailable.
 */

const HAIKU_MODEL = 'claude-haiku-4-5';

// Build #5 v2: parent directives. Server has service-role access so we read
// directly via the SECURITY DEFINER RPC ha_active_directives.
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const NIGEL_ID = '2e0e51c5-f120-4152-8aa1-041eeecc8165';

// focus_skill payload keys -> the zone where that skill lives. If the parent
// wants subtraction emphasized today, the stretch should be number-lab.
const SKILL_TO_ZONE = {
  'add_within_10':      'number-lab',
  'add_within_20':      'number-lab',
  'subtract_within_10': 'number-lab',
  'subtract_within_20': 'number-lab',
  'make_10':            'number-lab',
  'place_value':        'number-lab',
  'reading_fluency':    'word-tower',
  'sight_words':        'word-tower',
  'writing_sentences':  'writing',
};

// Human-readable skill labels for the Haiku prompt.
const SKILL_LABELS = {
  'add_within_10':      'addition within 10',
  'add_within_20':      'addition within 20',
  'subtract_within_10': 'subtraction within 10',
  'subtract_within_20': 'subtraction within 20',
  'make_10':            'the make-a-10 strategy',
  'place_value':        'place value',
  'reading_fluency':    'reading fluency',
  'sight_words':        'sight words',
  'writing_sentences':  'writing complete sentences',
};

// Subject/zone pool the model is allowed to pick from. Hero Hall is a trophy
// room \u2014 fine as a \"win\" celebration step, but not a learning task.
const ZONES = [
  { id: 'word-tower',  subject: 'reading',  label: 'Word Tower',        learn: true,  est: 7 },
  { id: 'story-time',  subject: 'reading',  label: 'Story Time',        learn: true,  est: 6 },
  { id: 'number-lab',  subject: 'math',     label: 'Number Lab',        learn: true,  est: 8 },
  { id: 'discovery',   subject: 'science',  label: 'Discovery Dome',    learn: true,  est: 6 },
  { id: 'explorer',    subject: 'social',   label: 'Explorer\u2019s Hall', learn: true,  est: 7 },
  { id: 'writing',     subject: 'writing',  label: 'Story Lab',         learn: true,  est: 8 },
  { id: 'hero-hall',   subject: 'trophy',   label: 'Hero Hall',         learn: false, est: 3 },
];

const UNLOCK_HINTS = [
  'Finish all 3 and unlock a surprise from the Squad!',
  'Three steps to a new character today.',
  'Complete the mission to grow your hero level!',
  'Crush all three and Ms. Humphrey will celebrate with you.',
];

// Reward character is picked from the *stretch* zone (the day\u2019s real work).
// Keys match HeroAcademy.Characters CHARACTERS[].id in js/characters.js.
const REWARD_CHARACTER_FOR_ZONE = {
  'number-lab': 'aurora',          // owl announcer covers math + general
  'word-tower': 'webly',           // web-slinger, wordtower-tagged
  'story-time': 'aurora',
  'discovery':  'carlo',           // cosmic plumber, discoverydome-tagged
  'explorer':   'shellback-squad', // quartet covers explorers
  'writing':    'aurora',
  'hero-hall':  'toybox-team',     // win-screen crew
};
const REWARD_FALLBACK = 'aurora';

function rewardCharacterForMission(m) {
  if (!m) return REWARD_FALLBACK;
  var stretchZone = m.stretch && m.stretch.zone_id;
  return REWARD_CHARACTER_FOR_ZONE[stretchZone] || REWARD_FALLBACK;
}

// ---------------------------------------------------------------------------
// Parent directives (Build #5 v2)
// ---------------------------------------------------------------------------

async function fetchActiveDirectives() {
  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) return [];
  try {
    const r = await fetch(SUPABASE_URL + '/rest/v1/rpc/ha_active_directives', {
      method: 'POST',
      headers: {
        apikey: SUPABASE_SERVICE_ROLE_KEY,
        Authorization: 'Bearer ' + SUPABASE_SERVICE_ROLE_KEY,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify({ p_child_id: NIGEL_ID }),
    });
    if (!r.ok) return [];
    const j = await r.json();
    return Array.isArray(j) ? j : [];
  } catch (_) {
    return [];
  }
}

// Sort active directives into the three buckets the mission cares about.
// request_quest_category is for the quest picker, not us — ignored here.
function classifyDirectives(directives) {
  const todayISO = new Date().toISOString().slice(0, 10);
  const skipZones = new Set();
  let focusSkill = null;
  const parentNotes = [];
  for (const d of (directives || [])) {
    const p = d.payload || {};
    if (d.directive_type === 'skip_zone_today') {
      const payloadDate = p.date || todayISO;
      if (payloadDate === todayISO && p.zone) skipZones.add(p.zone);
    } else if (d.directive_type === 'focus_skill') {
      // directives arrive newest-first; first wins.
      if (!focusSkill && p.skill) focusSkill = p.skill;
    } else if (d.directive_type === 'note_for_humphrey') {
      if (p.text) parentNotes.push({ text: String(p.text).slice(0, 300), by: d.created_by || 'parent' });
    }
  }
  return { skipZones, focusSkill, parentNotes };
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });

  let body = req.body;
  if (typeof body === 'string') { try { body = JSON.parse(body); } catch (_) { body = {}; } }
  if (!body || typeof body !== 'object') body = {};

  const zoneProgress = body.zone_progress || {};
  const recentZones = Array.isArray(body.recent_zones) ? body.recent_zones : [];
  const dayName = String(body.day_name || dayNameFromNumber(body.day_of_week));
  const homeworkDue = !!body.homework_due;
  const homeworkTopic = body.homework_topic || null;

  // Build #5 v2: read any active parent directives and let them shape today.
  const directives = await fetchActiveDirectives();
  const { skipZones, focusSkill, parentNotes } = classifyDirectives(directives);

  const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;

  let mission;
  if (ANTHROPIC_KEY) {
    try {
      mission = await generateWithHaiku({
        ANTHROPIC_KEY, dayName, zoneProgress, recentZones, homeworkDue, homeworkTopic,
        skipZones, focusSkill, parentNotes,
      });
    } catch (e) {
      mission = null;
    }
  }
  if (!mission) mission = fallbackMission({ zoneProgress, recentZones, homeworkDue, skipZones, focusSkill });

  // Final shape validation — also enforces skip rules in case Haiku ignored them.
  mission = validateAndPatch(mission, { skipZones, focusSkill });

  return res.status(200).json(mission);
}

function dayNameFromNumber(n) {
  const names = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  if (typeof n === 'number' && n >= 0 && n <= 6) return names[n];
  return names[new Date().getDay()];
}

async function generateWithHaiku({ ANTHROPIC_KEY, dayName, zoneProgress, recentZones, homeworkDue, homeworkTopic, skipZones, focusSkill, parentNotes }) {
  const skipSet = skipZones || new Set();
  // Filter the zone pool so Haiku can't even pick a skipped zone.
  const zonePool = ZONES
    .filter((z) => !skipSet.has(z.id))
    .map((z) => ({
      id: z.id,
      label: z.label,
      subject: z.subject,
      is_learning: z.learn,
      progress_pct: zoneProgress[z.id] || 0,
      minutes_estimate: z.est,
    }));

  // Compose parent context block (omitted entirely when there's no input).
  const parentLines = [];
  if (focusSkill && SKILL_LABELS[focusSkill]) {
    const targetZone = SKILL_TO_ZONE[focusSkill];
    parentLines.push(
      '  - Parent wants extra focus on ' + SKILL_LABELS[focusSkill] +
      (targetZone ? ' (lives in zone: ' + targetZone + ' — use it as the stretch if possible).' : '.')
    );
  }
  if (skipSet.size > 0) {
    parentLines.push('  - Parent asked to skip these zones today (already excluded from the pool): ' + Array.from(skipSet).join(', ') + '.');
  }
  if (parentNotes && parentNotes.length > 0) {
    parentNotes.slice(0, 3).forEach(function (n) {
      parentLines.push('  - Note from ' + n.by + ': "' + n.text + '" — weave the warmth of this into the warmup blurb if it fits naturally.');
    });
  }

  const systemPrompt = [
    'You are Ms. Humphrey designing today\u2019s 25-minute homeschool mission for Nigel \u2014 7 years old, 2nd grade, Maryland.',
    '',
    'Pick EXACTLY 3 zones from the allowed pool, in this order:',
    '  1. warmup   \u2014 something fun and easy, ideally something he\u2019s already comfortable with',
    '  2. stretch  \u2014 the real work for the day, in a subject he hasn\u2019t touched recently or shows lowest progress',
    '  3. win      \u2014 a quick crowd-pleaser to finish strong',
    '',
    'Rules:',
    '  - All three must come from the allowed pool.',
    '  - Cover at least 2 different subjects across the 3 picks.',
    '  - Avoid picking the same zone Nigel did most recently as the warmup, unless nothing else fits.',
    '  - If homework_due is true, the stretch MUST be \"number-lab\" (homework is math).',
    parentLines.length > 0 ? '\nParent guidance for today (Bianca/Josh sent these in the co-pilot — respect them):\n' + parentLines.join('\n') : '',
    '  - Each blurb is ONE short sentence written TO Nigel (\"Practice your ch- words with Webly.\") \u2014 not to parents.',
    '  - Minutes per step should be realistic: warmup ~5\u20137, stretch ~8\u201310, win ~3\u20136. Total close to 25.',
    '  - Output strictly valid JSON, nothing else. No markdown, no prose, no code fences.',
    '',
    'JSON shape:',
    '{',
    '  "warmup":  { "zone_id": "...", "title": "...", "blurb": "...", "minutes": 0 },',
    '  "stretch": { "zone_id": "...", "title": "...", "blurb": "...", "minutes": 0 },',
    '  "win":     { "zone_id": "...", "title": "...", "blurb": "...", "minutes": 0 },',
    '  "total_minutes": 0,',
    '  "unlock_hint": "..."',
    '}',
  ].filter(function (l) { return l !== ''; }).join('\n');

  const userPrompt = [
    'Day: ' + dayName,
    'Homework due today: ' + (homeworkDue ? ('yes (topic: ' + (homeworkTopic || 'math') + ')') : 'no'),
    'Recently visited zones (newest first): ' + (recentZones.length ? recentZones.join(', ') : 'none'),
    '',
    'Allowed zone pool with current progress:',
    JSON.stringify(zonePool, null, 2),
    '',
    'Design today\u2019s mission. Return JSON only.',
  ].join('\n');

  const r = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': ANTHROPIC_KEY,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: HAIKU_MODEL,
      max_tokens: 600,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    }),
  });
  if (!r.ok) throw new Error('anthropic ' + r.status);
  const json = await r.json();
  const text = (json.content || [])
    .filter((b) => b.type === 'text')
    .map((b) => b.text)
    .join('')
    .trim();
  // Strip code fences if present
  const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/i, '').trim();
  const parsed = JSON.parse(cleaned);
  return parsed;
}

function fallbackMission({ zoneProgress, recentZones, homeworkDue, skipZones, focusSkill }) {
  const skipSet = skipZones || new Set();
  // Pick least-recently-visited learning zones with lowest progress first.
  const recent = new Set(recentZones.slice(0, 2));
  const candidates = ZONES.filter((z) => z.learn && !skipSet.has(z.id)).slice();
  candidates.sort((a, b) => {
    var aRecent = recent.has(a.id) ? 1 : 0;
    var bRecent = recent.has(b.id) ? 1 : 0;
    if (aRecent !== bRecent) return aRecent - bRecent;
    return (zoneProgress[a.id] || 0) - (zoneProgress[b.id] || 0);
  });

  var warmupPool = ZONES.filter((z) => z.learn && !skipSet.has(z.id)).slice().sort((a, b) => (zoneProgress[b.id] || 0) - (zoneProgress[a.id] || 0));
  // If every learning zone got skipped (shouldn't happen in practice), back off.
  if (warmupPool.length === 0) warmupPool = ZONES.filter((z) => z.learn).slice();
  var warmup = warmupPool[0] || candidates[0] || ZONES[0];
  var stretchPool = candidates.filter((z) => z.id !== warmup.id);
  // Parent focus_skill wins over the default ordering for stretch selection.
  var focusZone = focusSkill && SKILL_TO_ZONE[focusSkill];
  if (focusZone && !skipSet.has(focusZone)) {
    var fz = stretchPool.find((z) => z.id === focusZone) || ZONES.find((z) => z.id === focusZone);
    if (fz) stretchPool = [fz].concat(stretchPool.filter((z) => z.id !== focusZone));
  } else if (homeworkDue) {
    var nl = stretchPool.find((z) => z.id === 'number-lab') || ZONES.find((z) => z.id === 'number-lab');
    if (nl && !skipSet.has('number-lab')) stretchPool = [nl].concat(stretchPool.filter((z) => z.id !== 'number-lab'));
  }
  var stretch = stretchPool[0] || candidates[0] || warmup;
  var win = candidates.find((z) => z.id !== warmup.id && z.id !== stretch.id) || ZONES.find((z) => z.id === 'hero-hall');

  return {
    warmup: {
      zone_id: warmup.id,
      title: warmup.label,
      blurb: 'Warm up with something you already love.',
      minutes: Math.min(7, warmup.est),
    },
    stretch: {
      zone_id: stretch.id,
      title: stretch.label,
      blurb: (focusZone && stretch.id === focusZone)
        ? 'Today\u2019s focus \u2014 dig in, hero.'
        : (homeworkDue && stretch.id === 'number-lab'
          ? 'Knock out today\u2019s homework, hero.'
          : 'Today\u2019s real challenge \u2014 take your time.'),
      minutes: Math.max(8, stretch.est),
    },
    win: {
      zone_id: win.id,
      title: win.label,
      blurb: 'Finish strong with a quick win.',
      minutes: Math.min(5, win.est || 5),
    },
    total_minutes: 20,
    unlock_hint: UNLOCK_HINTS[Math.floor(Math.random() * UNLOCK_HINTS.length)],
  };
}

function validateAndPatch(m, opts) {
  if (!m || typeof m !== 'object') m = {};
  opts = opts || {};
  const skipSet = opts.skipZones || new Set();
  const pool = new Set(ZONES.map((z) => z.id));
  // Pool of valid zones EXCLUDING parent-skipped ones, for repair.
  const allowedPool = ZONES.filter((z) => !skipSet.has(z.id));
  const usedZones = new Set();
  ['warmup', 'stretch', 'win'].forEach((slot) => {
    if (!m[slot] || typeof m[slot] !== 'object') m[slot] = {};
    var step = m[slot];
    var bad = !pool.has(step.zone_id) || skipSet.has(step.zone_id) || usedZones.has(step.zone_id);
    if (bad) {
      // Pick a sensible replacement from allowedPool that isn't already used.
      var fallbacks = { warmup: 'discovery', stretch: 'number-lab', win: 'hero-hall' };
      var preferred = fallbacks[slot];
      var replacement = null;
      if (!skipSet.has(preferred) && !usedZones.has(preferred)) {
        replacement = ZONES.find((zz) => zz.id === preferred);
      }
      if (!replacement) {
        replacement = allowedPool.find((zz) => !usedZones.has(zz.id));
      }
      if (!replacement) {
        // Last-resort: pick any zone not yet used, ignoring skip set.
        replacement = ZONES.find((zz) => !usedZones.has(zz.id)) || ZONES[0];
      }
      step.zone_id = replacement.id;
      step.title = replacement.label;
      // Reset blurb so we don't keep a hallucinated reference to the wrong zone.
      step.blurb = '';
    }
    usedZones.add(step.zone_id);
    if (typeof step.title !== 'string' || !step.title) {
      var z2 = ZONES.find((zz) => zz.id === step.zone_id);
      step.title = z2 ? z2.label : step.zone_id;
    }
    if (typeof step.blurb !== 'string') step.blurb = '';
    step.blurb = String(step.blurb).slice(0, 140);
    if (typeof step.minutes !== 'number' || step.minutes < 1 || step.minutes > 30) step.minutes = 6;
    step.minutes = Math.round(step.minutes);
  });
  m.total_minutes = (m.warmup.minutes || 0) + (m.stretch.minutes || 0) + (m.win.minutes || 0);
  if (typeof m.unlock_hint !== 'string' || !m.unlock_hint) {
    m.unlock_hint = UNLOCK_HINTS[0];
  }
  m.unlock_hint = String(m.unlock_hint).slice(0, 160);
  // Reward character is always picked server-side from the stretch zone so the
  // client doesn\u2019t have to know the mapping. Override any model hallucination.
  m.reward_character_key = rewardCharacterForMission(m);
  return m;
}
