const NIGEL={name:"Nigel",level:1};
const ZONES=[
{id:"word-tower",name:"Word Tower",subject:"Reading",emoji:"📖",desc:"Climb the tower of words. Practice reading, sight words, and stories with Ralphie.",image:"ralphie_reading",color:"emerald",glow:"rgba(46,194,126,0.5)",isNew:true},
{id:"number-lab",name:"Number Lab",subject:"Math",emoji:"🔢",desc:"Run number experiments! Master addition, subtraction, and more.",image:"ralphie_thinking",color:"electric",glow:"rgba(66,135,255,0.5)",isNew:true},
{id:"discovery",name:"Discovery Dome",subject:"Science",emoji:"🔬",desc:"Investigate the world. Animals, weather, space, and more.",image:"ralphie_magnifying",color:"violet",glow:"rgba(168,85,247,0.5)"},
{id:"explorer",name:"Explorer's Hall",subject:"Social Studies",emoji:"🌍",desc:"Travel through history, geography, and cultures around the world.",image:"ralphie_pointing",color:"orange",glow:"rgba(255,139,61,0.5)"},
{id:"creation",name:"Creation Studio",subject:"Art",emoji:"🎨",desc:"Paint, draw, and create. Bring your imagination to life.",image:"ralphie_painting",color:"magenta",glow:"rgba(236,72,153,0.5)"},
{id:"hero-hall",name:"Hero Hall",subject:"Trophy Room",emoji:"🏆",desc:"Meet the Surprise Squad! Collect characters by playing across every zone.",image:"ralphie_trophy",color:"cyan",glow:"rgba(20,184,212,0.5)",isNew:true},
{id:"sound-stage",name:"Sound Stage",subject:"Music",emoji:"🎵",desc:"Make music! Rhythm games, instruments, and learning songs.",image:"ralphie_guitar",color:"cyan",glow:"rgba(20,184,212,0.5)"},
{id:"gym",name:"Training Gym",subject:"Health & PE",emoji:"💪",desc:"Body strong, mind strong! Movement breaks and health learning.",image:"ralphie_flexing",color:"red",glow:"rgba(239,68,68,0.5)"},
{id:"writing",name:"Story Lab",subject:"Writing",emoji:"✍️",desc:"Write your own adventures. Spelling, sentences, and stories.",image:"ralphie_clapping",color:"violet",glow:"rgba(168,85,247,0.5)"}
];
const STATE_KEY="hero_academy_state_v1";
function loadState(){try{var r=localStorage.getItem(STATE_KEY);if(!r)return defaultState();return{...defaultState(),...JSON.parse(r)};}catch(e){return defaultState();}}
function defaultState(){return{coins:0,streak:0,level:1,xp:0,zoneProgress:{},zonesCompletedToday:0,arenaUnlocked:false,lastVisit:null,firstVisit:true,skillsMastered:[],currentMathSkill:"add_within_10",mathSkillProgress:{}};}
function saveState(){try{localStorage.setItem(STATE_KEY,JSON.stringify(state));}catch(e){}}
let state=loadState();
function getGreeting(){var h=new Date().getHours();if(h<12)return{eyebrow:"Good morning,",message:"Ready to train your powers today?"};if(h<17)return{eyebrow:"Good afternoon,",message:"Let's pick up where we left off!"};if(h<21)return{eyebrow:"Good evening,",message:"One more training session before bed?"};return{eyebrow:"Hi there,",message:"Up late training, huh? Let's go!"};}
const RALPHIE_LINES=["Welcome back!","Let's do this!","You got this!","Ready, hero?","I missed you!","Let's train!","What's first?"];
function rotateRalphieSpeech(){var bubble=document.getElementById("speechBubble"),text=bubble.querySelector(".speech-text"),i=0;setInterval(function(){bubble.classList.add("hidden");setTimeout(function(){i=(i+1)%RALPHIE_LINES.length;text.textContent=RALPHIE_LINES[i];bubble.classList.remove("hidden");},350);},5000);}
function renderZones(){var grid=document.getElementById("zonesGrid");grid.innerHTML="";ZONES.forEach(function(zone){var progress=state.zoneProgress[zone.id]||0;var card=document.createElement("button");card.className="zone-card";card.setAttribute("data-zone",zone.id);card.setAttribute("aria-label","Enter "+zone.name);card.innerHTML=(zone.isNew&&progress===0?'<span class="zone-badge">NEW</span>':"")+
'<span class="zone-emoji" aria-hidden="true">'+zone.emoji+'</span>'+
'<div class="zone-img-wrap"><div class="zone-img-glow"></div><img src="assets/ralphie/'+zone.image+'.webp" alt="" class="zone-img" loading="lazy"></div>'+
'<div class="zone-name">'+zone.name+'</div><div class="zone-subject">'+zone.subject+'</div>'+
'<div class="zone-progress"><div class="zone-progress-track"><div class="zone-progress-fill" style="width:'+progress+'%"></div></div><span class="zone-progress-pct">'+progress+'%</span></div>';
card.addEventListener("click",function(){openZoneModal(zone);});grid.appendChild(card);});}
function updateHUD(){document.getElementById("coinCount").textContent=state.coins;document.getElementById("streakCount").textContent=state.streak;document.getElementById("avatarLevel").textContent=state.level;document.getElementById("dailyDone").textContent=state.zonesCompletedToday;var pct=Math.min(100,(state.zonesCompletedToday/3)*100);document.getElementById("dailyProgress").style.width=pct+"%";var ab=document.getElementById("arenaBtn"),ad=document.getElementById("arenaDesc");if(state.arenaUnlocked){ab.disabled=false;ab.querySelector(".arena-btn-text").textContent="PLAY";ab.querySelector(".arena-btn-icon").textContent="🏀";ad.textContent="Game time unlocked!";}else{ab.disabled=true;ab.querySelector(".arena-btn-text").textContent="LOCKED";ab.querySelector(".arena-btn-icon").textContent="🔒";ad.textContent="Complete a training zone to unlock!";}}
function openZoneModal(zone){var modal=document.getElementById("zoneModal"),card=document.getElementById("zoneModalCard"),img=document.getElementById("zoneModalRalphie"),title=document.getElementById("zoneModalTitle"),desc=document.getElementById("zoneModalDesc"),progress=document.getElementById("zoneModalProgress"),enterBtn=document.getElementById("zoneModalEnter");var cm={emerald:["#2ec27e","#4dd99c","rgba(46,194,126,0.4)"],electric:["#4287ff","#6ba6ff","rgba(66,135,255,0.4)"],violet:["#a855f7","#c98aff","rgba(168,85,247,0.4)"],orange:["#ff8b3d","#ffa86b","rgba(255,139,61,0.4)"],magenta:["#ec4899","#f471b5","rgba(236,72,153,0.4)"],cyan:["#14b8d4","#38ccea","rgba(20,184,212,0.4)"],red:["#ef4444","#ff6363","rgba(239,68,68,0.4)"]};var c=cm[zone.color]||cm.electric;card.style.setProperty("--zone-modal-color",c[0]);card.style.setProperty("--zone-modal-color-bright",c[1]);card.style.setProperty("--zone-modal-glow",c[2]);img.src="assets/ralphie/"+zone.image+".webp";img.alt="Ralphie ready for "+zone.name;title.textContent=zone.emoji+" "+zone.name;desc.textContent=zone.desc;progress.textContent=(state.zoneProgress[zone.id]||0)+"%";enterBtn.onclick=function(){closeZoneModal();if(zone.id==="number-lab"){window.location.href="number-lab.html";}else if(zone.id==="explorer"){window.location.href="diner-lanes.html";}else if(zone.id==="hero-hall"){window.location.href="hero-hall.html";}else{completeSession(zone);showRalphieSpeech(zone.name+" coming soon!");}};modal.hidden=false;}
function closeZoneModal(){document.getElementById("zoneModal").hidden=true;}
function completeSession(zone){var c=state.zoneProgress[zone.id]||0;state.zoneProgress[zone.id]=Math.min(100,c+15);state.coins+=3;state.zonesCompletedToday+=1;if(state.zonesCompletedToday===1)state.streak+=1;state.arenaUnlocked=true;saveState();renderZones();updateHUD();showRalphieSpeech("+3 coins from "+zone.name+"!");burstConfetti();}
function burstConfetti(){var colors=["#ffd147","#ec4899","#4287ff","#2ec27e","#a855f7","#ff8b3d"];var ct=document.createElement("div");ct.style.cssText="position:fixed;inset:0;pointer-events:none;z-index:200;overflow:hidden";for(var i=0;i<60;i++){var p=document.createElement("div"),sz=6+Math.random()*8,cl=colors[Math.floor(Math.random()*colors.length)],sx=30+Math.random()*40,dr=(Math.random()-0.5)*60,rt=Math.random()*720,du=1.5+Math.random()*1;p.style.cssText="position:absolute;left:"+sx+"%;top:50%;width:"+sz+"px;height:"+sz+"px;background:"+cl+";border-radius:"+(Math.random()>0.5?"50%":"2px")+";animation:confetti-fall "+du+"s "+Math.random()*0.4+"s cubic-bezier(0.2,0.7,0.3,1) forwards;--drift:"+dr+"vw;--rot:"+rt+"deg;";ct.appendChild(p);}document.body.appendChild(ct);setTimeout(function(){ct.remove();},3000);}
(function(){var s=document.createElement("style");s.textContent="@keyframes confetti-fall{0%{transform:translate(0,-50vh) rotate(0);opacity:1;}100%{transform:translate(var(--drift),60vh) rotate(var(--rot));opacity:0;}}";document.head.appendChild(s);})();
function showRalphieSpeech(text){var b=document.getElementById("speechBubble"),t=b.querySelector(".speech-text");b.classList.add("hidden");setTimeout(function(){t.textContent=text;b.classList.remove("hidden");},300);}
function setupHumphrey(){var btn=document.getElementById("humphreyBtn");btn.addEventListener("click",function(){btn.classList.add("speaking");showRalphieSpeech("Miss Humphrey says hi!");setTimeout(function(){btn.classList.remove("speaking");},2200);});}
function maybeShowWelcome(){if(state.firstVisit){var o=document.getElementById("welcomeOverlay");o.hidden=false;document.getElementById("welcomeBtn").addEventListener("click",function(){o.style.opacity="0";o.style.transition="opacity 0.4s";setTimeout(function(){o.hidden=true;state.firstVisit=false;saveState();},400);},{once:true});}}
function setupRalphieTap(){var r=document.getElementById("heroRalphie"),poses=["ralphie_waving","ralphie_cheering","ralphie_thinking","ralphie_surprised","ralphie_flexing"],i=0;r.addEventListener("click",function(){i=(i+1)%poses.length;r.style.transform="scale(0.85) rotate(-10deg)";setTimeout(function(){r.src="assets/ralphie/"+poses[i]+".webp";r.style.transform="";},150);showRalphieSpeech(["Hey!","Boop!","Hi!","Look!","Yes!"][i]);});}
function init(){var g=getGreeting();document.getElementById("timeGreeting").textContent=g.eyebrow;document.getElementById("heroMessage").textContent=g.message;renderZones();updateHUD();setupHumphrey();setupRalphieTap();rotateRalphieSpeech();maybeShowWelcome();document.getElementById("zoneModalClose").addEventListener("click",closeZoneModal);document.querySelector(".zone-modal-backdrop").addEventListener("click",closeZoneModal);document.getElementById("arenaBtn").addEventListener("click",function(){if(!this.disabled){showRalphieSpeech("Let's play! 🏀");burstConfetti();}});document.getElementById("avatarBtn").addEventListener("click",function(){showRalphieSpeech("Customization coming soon!");});state.lastVisit=Date.now();saveState();setupHomework();}
function _haTodayKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function _haSimulate(){try{var p=new URLSearchParams(location.search);var s=p.get('simulate');var nRaw=p.get('progress');if(s==='tue'||s==='thu'){var sim={day:s==='tue'?2:4,name:s==='tue'?'Tuesday':'Thursday',progress:Math.max(0,Math.min(10,parseInt(nRaw||'0',10)||0)),fromUrl:true};try{sessionStorage.setItem('ha_simulate',JSON.stringify(sim));}catch(e){}try{localStorage.removeItem('ha_homework_announced_'+_haTodayKey());var k='ha_homework_'+_haTodayKey();var raw=localStorage.getItem(k);if(raw){var hw=JSON.parse(raw);hw.completed_count=sim.progress;hw.completed_at=sim.progress>=hw.target?new Date().toISOString():null;localStorage.setItem(k,JSON.stringify(hw));}}catch(e){}return sim;}var stored=sessionStorage.getItem('ha_simulate');if(stored){try{return JSON.parse(stored);}catch(e){}}}catch(e){}return null;}
function _haIsHomeworkDay(){if(_haSimulate())return true;var d=new Date().getDay();return d===2||d===4;}
function _haDayName(){var s=_haSimulate();if(s)return s.name;return ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][new Date().getDay()];}
function _haHumanizeSkill(id){if(!id)return 'Math Practice';return id.split('_').map(function(p){return p.charAt(0).toUpperCase()+p.slice(1);}).join(' ');}
function loadHomework(){if(!_haIsHomeworkDay())return null;var k='ha_homework_'+_haTodayKey();var raw=localStorage.getItem(k);if(raw){try{return JSON.parse(raw);}catch(e){}}var sim=_haSimulate();var initProgress=sim?sim.progress:0;var hw={dateKey:_haTodayKey(),dayName:_haDayName(),topic:state.currentMathSkill||'add_within_10',topicName:_haHumanizeSkill(state.currentMathSkill),target:10,completed_count:initProgress,completed_at:initProgress>=10?new Date().toISOString():null};localStorage.setItem(k,JSON.stringify(hw));return hw;}
function renderHomework(){var card=document.getElementById('homeworkCard');if(!card)return;var hw=loadHomework();if(!hw){card.hidden=true;return;}card.hidden=false;var done=hw.completed_count>=hw.target;card.classList.toggle('done',done);document.getElementById('hwTitle').textContent=hw.topicName;document.getElementById('hwProgress').textContent=Math.min(hw.completed_count,hw.target)+' / '+hw.target;document.getElementById('hwFill').style.width=Math.min(100,Math.round(hw.completed_count/hw.target*100))+'%';document.getElementById('hwStatus').textContent=done?'✅ All done!':"Today's Homework";document.getElementById('hwStart').textContent=done?'PRACTICE MORE':'START';}
function setupHomework(){renderHomework();var startBtn=document.getElementById('hwStart');if(startBtn&&!startBtn._hwBound){startBtn._hwBound=true;startBtn.addEventListener('click',function(){var sim=_haSimulate();var qs=sim&&sim.fromUrl?('?simulate='+(sim.day===2?'tue':'thu')):'';window.location.href='number-lab.html'+qs;});}var hw=loadHomework();if(!hw)return;var ak='ha_homework_announced_'+_haTodayKey();if(!localStorage.getItem(ak)&&hw.completed_count<hw.target){setTimeout(function(){if(window.HeroAcademy&&window.HeroAcademy.Humphrey){window.HeroAcademy.Humphrey.say('homework-assigned',{kidName:'Nigel',topic:hw.topicName,dayName:hw.dayName});}},2800);localStorage.setItem(ak,'1');}}
document.addEventListener("DOMContentLoaded",init);