var STATE_KEY="hero_academy_state_v1";
var session={currentSkillId:null,currentProblem:null,streakInSkill:0,strikesOnProblem:0,problemsAttempted:0,problemsCorrect:0,sessionCoins:0,showingExample:true};
function loadState(){try{var r=localStorage.getItem(STATE_KEY);return r?JSON.parse(r):defaultState();}catch(e){return defaultState();}}
function defaultState(){return{coins:0,streak:0,level:1,xp:0,zoneProgress:{},zonesCompletedToday:0,arenaUnlocked:false,lastVisit:null,firstVisit:false,skillsMastered:[],currentMathSkill:"add_within_10",mathSkillProgress:{}};}
function saveState(){try{localStorage.setItem(STATE_KEY,JSON.stringify(state));}catch(e){}}
var state=loadState();
function init(){session.currentSkillId=state.currentMathSkill||"add_within_10";session.streakInSkill=state.mathSkillProgress[session.currentSkillId]||0;loadSkill(session.currentSkillId);setupHumphrey();}
function loadSkill(id){var sk=MATH_SKILLS[id];if(!sk){showAllDone();return;}session.currentSkillId=id;session.streakInSkill=state.mathSkillProgress[id]||0;session.strikesOnProblem=0;document.getElementById("currentSkillName").textContent=sk.name;document.getElementById("masteryTarget").textContent=sk.masteryCount;document.getElementById("streakInSkill").textContent=session.streakInSkill;if(session.streakInSkill===0&&session.problemsAttempted===0)showWorkedExample(sk);else showProblem();}
function showWorkedExample(sk){document.getElementById("exampleCard").hidden=false;document.getElementById("problemCard").hidden=true;document.getElementById("masteryCard").hidden=true;document.getElementById("exampleProblem").textContent=sk.workedExample.problem;document.getElementById("exampleExplanation").textContent=sk.workedExample.explanation;document.getElementById("exampleVisual").textContent=sk.workedExample.visualHint||"";document.getElementById("exampleGotIt").onclick=function(){document.getElementById("exampleCard").hidden=true;showProblem();};}
function showProblem(){var sk=MATH_SKILLS[session.currentSkillId];session.currentProblem=sk.generate();session.strikesOnProblem=0;document.getElementById("problemCard").hidden=false;document.getElementById("masteryCard").hidden=true;renderDots(sk.masteryCount);document.getElementById("problemNum").textContent=session.problemsAttempted+1;document.getElementById("labRalphie").src="assets/ralphie/ralphie_thinking.webp";document.getElementById("labRalphie").classList.remove("celebrate","shake");document.getElementById("labSpeech").hidden=true;document.getElementById("problemQuestion").textContent=session.currentProblem.question;var ch=document.getElementById("answerChoices");ch.innerHTML="";session.currentProblem.choices.forEach(function(c){var btn=document.createElement("button");btn.className="answer-btn";btn.textContent=c;btn.onclick=function(){handleAnswer(c,btn);};ch.appendChild(btn);});document.getElementById("feedback").hidden=true;document.getElementById("hintBtn").classList.remove("visible");document.getElementById("hintDisplay").hidden=true;}
function renderDots(t){var c=document.getElementById("masteryDots");c.innerHTML="";for(var i=0;i<t;i++){var d=document.createElement("div");d.className="mastery-dot"+(i<session.streakInSkill?" filled":"");c.appendChild(d);}}
function handleAnswer(choice,btn){document.querySelectorAll(".answer-btn").forEach(function(b){b.disabled=true;});String(choice)===String(session.currentProblem.answer)?handleCorrect(btn):handleWrong(btn);}
function handleCorrect(btn){btn.classList.add("correct");var r=document.getElementById("labRalphie");r.src="assets/ralphie/ralphie_cheering.webp";r.classList.add("celebrate");showLabSpeech(["YES!","Got it!","Boom!","POW!","Nice!"][Math.floor(Math.random()*5)]);var fb=document.getElementById("feedback");fb.className="feedback success";fb.innerHTML='<span class="feedback-emoji">⚡</span>That\'s right!';fb.hidden=false;if(session.strikesOnProblem===0){session.streakInSkill+=1;state.mathSkillProgress[session.currentSkillId]=session.streakInSkill;}session.problemsAttempted+=1;session.problemsCorrect+=1;session.sessionCoins+=1;document.getElementById("streakInSkill").textContent=session.streakInSkill;document.getElementById("sessionCoins").textContent=session.sessionCoins;renderDots(MATH_SKILLS[session.currentSkillId].masteryCount);saveState();var sk=MATH_SKILLS[session.currentSkillId];if(window.HeroAcademy&&window.HeroAcademy.Humphrey&&session.streakInSkill<sk.masteryCount){var H=window.HeroAcademy.Humphrey;if(session.streakInSkill===10){H.say("streak-10",{kidName:"Nigel",streak:10})}else if(session.streakInSkill===5){H.say("streak-5",{kidName:"Nigel",streak:5})}else if(session.streakInSkill===3){H.say("streak-3",{kidName:"Nigel",streak:3})}else{H.say("correct-answer",{kidName:"Nigel"})}}if(session.streakInSkill>=sk.masteryCount)setTimeout(function(){showMastery(sk);},1200);else setTimeout(showProblem,1400);}
function handleWrong(btn){btn.classList.add("wrong");session.strikesOnProblem+=1;session.streakInSkill=0;state.mathSkillProgress[session.currentSkillId]=0;document.getElementById("streakInSkill").textContent=0;renderDots(MATH_SKILLS[session.currentSkillId].masteryCount);var r=document.getElementById("labRalphie");r.src="assets/ralphie/ralphie_sad.webp";r.classList.add("shake");setTimeout(function(){r.classList.remove("shake");},500);var sk=MATH_SKILLS[session.currentSkillId];var fb=document.getElementById("feedback");if(session.strikesOnProblem===1){if(window.HeroAcademy&&window.HeroAcademy.Humphrey){window.HeroAcademy.Humphrey.say("wrong-answer",{kidName:"Nigel"})}fb.className="feedback tryAgain";fb.innerHTML='<span class="feedback-emoji">🤔</span>Almost! Look one more time.';fb.hidden=false;showLabSpeech("Almost!");setTimeout(function(){document.getElementById("hintBtn").classList.add("visible");},500);setTimeout(function(){document.querySelectorAll(".answer-btn").forEach(function(b){if(!b.classList.contains("wrong"))b.disabled=false;});},1000);}else{var wt=sk.walkthrough?sk.walkthrough(session.currentProblem):sk.workedExample.explanation;fb.className="feedback scaffold";fb.innerHTML='<span class="feedback-emoji">👩‍🏫</span><strong>Let me show you, Nigel.</strong><br><br>'+wt+'<br><br>Tap <strong>'+session.currentProblem.answer+'</strong> to lock it in.';fb.hidden=false;showLabSpeech("Let\'s do it together.");document.getElementById("hintBtn").classList.remove("visible");document.getElementById("hintDisplay").hidden=true;setTimeout(function(){document.querySelectorAll(".answer-btn").forEach(function(b){if(String(b.textContent)===String(session.currentProblem.answer)){b.disabled=false;b.style.animation="correct-pulse 1.2s ease-in-out infinite";b.style.borderColor="var(--gold)";b.style.boxShadow="0 0 24px rgba(255,209,71,0.6)";b.onclick=function(){b.style.animation="";b.classList.add("correct");session.problemsAttempted+=1;setTimeout(showProblem,1000);};}});},1500);}}
document.addEventListener("DOMContentLoaded",function(){document.getElementById("hintBtn").addEventListener("click",function(){var sk=MATH_SKILLS[session.currentSkillId];var h=sk.hints[Math.min(session.strikesOnProblem-1,sk.hints.length-1)]||sk.hints[0];document.getElementById("hintText").textContent=h;document.getElementById("hintDisplay").hidden=false;document.getElementById("hintBtn").classList.remove("visible");});});
function showLabSpeech(t){var s=document.getElementById("labSpeech");document.getElementById("labSpeechText").textContent=t;s.hidden=false;setTimeout(function(){s.hidden=true;},2000);}
function showMastery(sk){if(window.HeroAcademy&&window.HeroAcademy.Humphrey){window.HeroAcademy.Humphrey.say("mastery-achieved",{kidName:"Nigel",topic:sk.name})}document.getElementById("problemCard").hidden=true;document.getElementById("masteryCard").hidden=false;document.getElementById("masterySkillName").textContent=sk.name;session.sessionCoins+=5;state.coins+=session.sessionCoins;if(!state.skillsMastered.includes(sk.id))state.skillsMastered.push(sk.id);if(sk.nextSkill){state.currentMathSkill=sk.nextSkill;state.mathSkillProgress[sk.nextSkill]=0;}var m=state.skillsMastered.filter(function(s){return MATH_SKILLS[s];}).length;state.zoneProgress["number-lab"]=Math.min(100,Math.round(m/MATH_SKILL_ORDER.length*100));state.zonesCompletedToday=(state.zonesCompletedToday||0)+1;state.arenaUnlocked=true;saveState();burstConfetti();document.getElementById("masteryNext").onclick=function(){if(sk.nextSkill){session.problemsAttempted=0;session.streakInSkill=0;loadSkill(sk.nextSkill);}else showAllDone();};document.getElementById("masteryRest").onclick=function(){window.location.href="index.html";};}
function showAllDone(){if(window.HeroAcademy&&window.HeroAcademy.Humphrey){window.HeroAcademy.Humphrey.say("mastery-achieved",{kidName:"Nigel",topic:"all your math skills"})}document.getElementById("masteryCard").hidden=false;document.getElementById("problemCard").hidden=true;document.getElementById("exampleCard").hidden=true;document.querySelector(".mastery-title").textContent="ALL SKILLS MASTERED!";document.getElementById("masterySkillName").textContent="You\'re a Math Hero, Nigel.";document.getElementById("masteryNext").textContent="BACK TO MAP";document.getElementById("masteryNext").onclick=function(){window.location.href="index.html";};document.getElementById("masteryRest").hidden=true;}
function burstConfetti(){var colors=["#ffd147","#ec4899","#4287ff","#2ec27e","#a855f7","#ff8b3d"];var ct=document.createElement("div");ct.style.cssText="position:fixed;inset:0;pointer-events:none;z-index:200;overflow:hidden";for(var i=0;i<70;i++){var p=document.createElement("div"),sz=6+Math.random()*10,cl=colors[Math.floor(Math.random()*colors.length)],sx=20+Math.random()*60,dr=(Math.random()-0.5)*70,rt=Math.random()*720,du=1.5+Math.random()*1.2;p.style.cssText="position:absolute;left:"+sx+"%;top:40%;width:"+sz+"px;height:"+sz+"px;background:"+cl+";border-radius:"+(Math.random()>0.5?"50%":"2px")+";animation:confetti-fall "+du+"s "+Math.random()*0.4+"s cubic-bezier(0.2,0.7,0.3,1) forwards;--drift:"+dr+"vw;--rot:"+rt+"deg;";ct.appendChild(p);}document.body.appendChild(ct);setTimeout(function(){ct.remove();},3500);}
(function(){var s=document.createElement("style");s.textContent="@keyframes confetti-fall{0%{transform:translate(0,-50vh) rotate(0);opacity:1;}100%{transform:translate(var(--drift),80vh) rotate(var(--rot));opacity:0;}}";document.head.appendChild(s);})();
function setupHumphrey(){var btn=document.getElementById("humphreyBtn");btn.addEventListener("click",function(){btn.classList.add("speaking");showLabSpeech("Miss Humphrey says hi!");setTimeout(function(){btn.classList.remove("speaking");},2200);});}
document.addEventListener("DOMContentLoaded",init);