-- v140 Class Time migration
-- Tables: ha_class_time_lessons (date-keyed cache), ha_events helper (if missing)
-- RPCs: ha_record_event (used by /api/record-event endpoint pattern)

-- 1. Lessons cache table (date PRIMARY KEY = one canonical lesson per day)
CREATE TABLE IF NOT EXISTS public.ha_class_time_lessons (
  date         date PRIMARY KEY,
  lesson       jsonb NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.ha_class_time_lessons IS 'Daily Class Time lesson plans generated by Haiku 4.5. One row per ET date.';

CREATE INDEX IF NOT EXISTS ha_class_time_lessons_generated_at_idx
  ON public.ha_class_time_lessons (generated_at DESC);

-- 2. Generic events table (in case it doesn't already exist — guarded by IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS public.ha_events (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id    uuid NOT NULL,
  event_type  text NOT NULL,
  payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ha_events_child_type_created_idx
  ON public.ha_events (child_id, event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS ha_events_created_at_idx
  ON public.ha_events (created_at DESC);

-- 3. RPC: ha_record_event — generic telemetry sink (used by /api/record-event)
CREATE OR REPLACE FUNCTION public.ha_record_event(
  p_child_id   uuid,
  p_event_type text,
  p_payload    jsonb DEFAULT '{}'::jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id uuid;
BEGIN
  INSERT INTO public.ha_events (child_id, event_type, payload)
  VALUES (p_child_id, p_event_type, COALESCE(p_payload, '{}'::jsonb))
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ha_record_event(uuid, text, jsonb) TO anon, authenticated, service_role;

-- 4. RPC: ha_get_today_voice_usage — voice cap check (counts events of type '%_voice' today ET)
-- This function may already exist with the same signature. We DROP + CREATE to ensure it's the v140 logic.
DROP FUNCTION IF EXISTS public.ha_get_today_voice_usage(uuid);

CREATE OR REPLACE FUNCTION public.ha_get_today_voice_usage(p_child_id uuid)
RETURNS TABLE (count integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_day_start timestamptz;
  v_day_end   timestamptz;
BEGIN
  -- America/New_York day window
  v_day_start := date_trunc('day', (now() AT TIME ZONE 'America/New_York'))::timestamptz AT TIME ZONE 'America/New_York';
  v_day_end   := v_day_start + interval '1 day';

  RETURN QUERY
    SELECT COUNT(*)::int AS count
    FROM public.ha_events
    WHERE child_id = p_child_id
      AND event_type LIKE '%_voice'
      AND created_at >= v_day_start
      AND created_at <  v_day_end;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ha_get_today_voice_usage(uuid) TO anon, authenticated, service_role;

-- 5. RPC: ha_class_time_history — Last N days of class completions for a child (for dashboard later)
CREATE OR REPLACE FUNCTION public.ha_class_time_history(
  p_child_id uuid,
  p_days     int DEFAULT 14
)
RETURNS TABLE (
  date              date,
  completed_at      timestamptz,
  topics_completed  int,
  total_topics      int,
  duration_sec      int,
  reason            text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
    SELECT
      (payload->>'lesson_date')::date AS date,
      created_at                       AS completed_at,
      COALESCE((payload->>'topics_completed')::int, 0) AS topics_completed,
      COALESCE((payload->>'total_topics')::int, 0)     AS total_topics,
      COALESCE((payload->>'duration_sec')::int, 0)     AS duration_sec,
      COALESCE(payload->>'reason', '')                  AS reason
    FROM public.ha_events
    WHERE child_id = p_child_id
      AND event_type = 'class_time_complete'
      AND created_at >= now() - (p_days || ' days')::interval
    ORDER BY created_at DESC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ha_class_time_history(uuid, int) TO anon, authenticated, service_role;

-- 6. Read access to ha_class_time_lessons via RPC (avoids needing RLS rules)
CREATE OR REPLACE FUNCTION public.ha_get_class_time_lesson(p_date date)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lesson jsonb;
BEGIN
  SELECT lesson INTO v_lesson
  FROM public.ha_class_time_lessons
  WHERE date = p_date;
  RETURN v_lesson;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ha_get_class_time_lesson(date) TO anon, authenticated, service_role;

-- 7. RLS: lock the tables down — only service_role writes via RPC; reads via RPC only.
ALTER TABLE public.ha_class_time_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ha_events ENABLE ROW LEVEL SECURITY;

-- (No policies → all anon access denied; RPCs use SECURITY DEFINER and run as table owner.)
